parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\GetRandomDog:
        autowire: true
        autoconfigure: true
        public: false
        arguments:
            $dogRepository: '@App\Repository\DogRepository'
